apiVersion: apps/v1
kind: Deployment
metadata:
  name: unl3ash
  namespace: {{ .Values.namespace.name }}
  labels:
    app: unl3ash
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: unl3ash
  template:
    metadata:
      labels:
        app: unl3ash
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: unl3ash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: BUCKET_NAME
              value: {{ .Values.env.BUCKET_NAME | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
