replicaCount: 1

image:
  repository: "532150070616.dkr.ecr.us-east-1.amazonaws.com/unl3ash"
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
  name: unl3ash-service
  type: LoadBalancer
  port: 80
  targetPort: 3000

namespace:
  name: unl3ash

serviceAccount:
  name: unl3ash
  iamRoleArn: "arn:aws:iam::532150070616:role/unl3ash-s3-access"

env:
  BUCKET_NAME: "unl3ash-bucket"
